server:
  port: 7777
  servlet:
    context-path: /
spring:
  redis:
    host: localhost
    port: 6379
    password: redis


oli:
  rpc:
    proxy: jdk
    protocol: netty
    redis:
      host: http://localhost:6379
      password: redis
    params:
      loadbalance: random
